/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderLink: typeof import('./src/components/globals/header/HeaderLink.vue')['default']
    HeaderLinks: typeof import('./src/components/globals/header/HeaderLinks.vue')['default']
    IconButton: typeof import('./src/components/globals/header/IconButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/globals/header/TheHeader.vue')['default']
    TheLogo: typeof import('./src/components/globals/TheLogo.vue')['default']
    TheProject: typeof import('./src/components/work/TheProject.vue')['default']
    TheTitle: typeof import('./src/components/globals/TheTitle.vue')['default']
    TheVisualiser: typeof import('./src/components/audioVisualiser/TheVisualiser.vue')['default']
    TheWork: typeof import('./src/components/work/TheWork.vue')['default']
  }
}
